# to activate this config, put the following line in ~/.alacritty.toml:
#import = ["~/src/dotfiles/.alacritty.toml"]
# (note, the config will not reload unless you re-save the config in home dir)

[window]
startup_mode = 'Fullscreen'
#startup_mode = 'SimpleFullscreen'
#startup_mode = 'Maximized'

[font]
# fonts must be downloaded to ~/.fonts.
normal.family = 'JetBrainsMonoNerdFont'
#bold.family = 'JetBrainsMonoNerdFont'
size = 12.0

